// DIRECTORY.md is generated by templates/directory-gen.mjs from directory-catalog.json.
// Ordered text blocks preserve the old directory verbatim. A path owns one tracked file;
// paths owns a legacy grouped block; path: null is prose. Each covered path occurs once.
// --check (default) certifies coverage and rendering; --write refuses invalid coverage.
// CRLF checkouts compare as LF, like git's text blobs. No packages or machine writes.
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const CATALOG = "templates/directory-catalog.json";
export const HEADER = "<!-- generated by " + "templates/directory-gen.mjs from templates/directory-catalog.json; edit the catalog, then run --write; hand edits here are overwritten and the pointer net goes red -->";
const norm = (s) => s.replace(/\r\n/g, "\n");
const excepted = (p) => /^memory\/[^/]+\.md$/.test(p) || p.startsWith("lessons/platforms/");

// The pointer net's disk fallback: ignored machine classes stay outside the kit inventory.
export function getInventory(root, git = execFileSync) {
  try {
    const out = git("git", ["ls-files", "-z"], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
    return { files: new Set(out.split("\0").filter(Boolean)), degraded: false };
  } catch {
    const files = new Set();
    const walk = (dir = "") => {
      for (const e of fs.readdirSync(path.join(root, dir), { withFileTypes: true })) {
        if ([".git", ".claude", "node_modules", "archives", ".playwright-cli"].includes(e.name)) continue;
        const rel = dir ? `${dir}/${e.name}` : e.name;
        if (/LOCAL-ONLY|\.code-workspace$/.test(rel)) continue;
        if (e.isDirectory()) walk(rel); else files.add(rel);
      }
    };
    walk();
    return { files, degraded: true };
  }
}

export function validateCatalog(catalog, tracked) {
  const errors = [], owners = new Map();
  if (!Array.isArray(catalog)) return ["catalog must be an ordered array"];
  for (const [i, entry] of catalog.entries()) {
    const label = `catalog entry ${i + 1}`;
    if (!entry || typeof entry !== "object" || Array.isArray(entry)) { errors.push(`${label}: expected an object`); continue; }
    const single = Object.hasOwn(entry, "path"), grouped = Object.hasOwn(entry, "paths");
    if (single === grouped || Object.keys(entry).some((k) => !["path", "paths", "text"].includes(k))) {
      errors.push(`${label}: use exactly path or paths, plus text`); continue;
    }
    if (typeof entry.text !== "string" || entry.text.includes("\r")) errors.push(`${label}: text must be an LF string`);
    let paths;
    if (single && entry.path === null) paths = [];
    else if (single && typeof entry.path === "string") paths = [entry.path];
    else if (grouped && Array.isArray(entry.paths) && entry.paths.length) paths = entry.paths;
    else { errors.push(`${label}: invalid path or empty paths`); continue; }
    if (paths.length && (typeof entry.text !== "string" || !entry.text.trim())) errors.push(`${label}: a file entry needs visible text`);
    for (const p of paths) {
      if (typeof p !== "string" || !p || p.includes("\\") || p.includes("\0") || p.split("/").some((s) => !s || s === "." || s === "..") || /^[A-Za-z]:/.test(p)) {
        errors.push(`${label}: expected an exact relative POSIX file path`); continue;
      }
      if (owners.has(p)) errors.push(`${p}: more than one catalog match (entries ${owners.get(p)} and ${i + 1})`);
      else owners.set(p, i + 1);
      if (!tracked.has(p)) errors.push(`${p}: catalog path is untracked`);
      if (excepted(p)) errors.push(`${p}: indexed in its own manifest, never in DIRECTORY`);
    }
  }
  for (const p of tracked) if (!excepted(p) && !owners.has(p)) errors.push(`${p}: tracked file has no catalog entry`);
  return errors;
}

export function renderDirectory(catalog) {
  return HEADER + "\n" + catalog.map((entry) => entry.text).join("\n");
}

export function firstDifference(actual, expected) {
  const a = norm(actual).split("\n"), b = expected.split("\n");
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    if (a[i] !== b[i]) return `DIRECTORY.md differs at line ${i + 1}\n  expected: ${JSON.stringify(b[i] ?? "<EOF>")}\n  actual:   ${JSON.stringify(a[i] ?? "<EOF>")}`;
  }
  return null;
}

export function checkDirectory(root = ROOT, { write = false, git = execFileSync } = {}) {
  const inventory = getInventory(root, git);
  const notes = inventory.degraded ? ["git unavailable: treating every kit file on disk as tracked (degraded-strict)"] : [];
  let catalog;
  try { catalog = JSON.parse(fs.readFileSync(path.join(root, CATALOG), "utf8")); }
  catch (err) { return { ok: false, notes, errors: [`${CATALOG}: ${err.message}`] }; }
  const errors = validateCatalog(catalog, inventory.files);
  for (const p of inventory.files) if (!fs.existsSync(path.join(root, p))) errors.push(`${p}: tracked file is missing on disk`);
  if (errors.length) return { ok: false, notes, errors };
  const rendered = renderDirectory(catalog), target = path.join(root, "DIRECTORY.md");
  if (write) fs.writeFileSync(target, rendered, "utf8");
  else {
    let actual;
    try { actual = fs.readFileSync(target, "utf8"); }
    catch (err) { return { ok: false, notes, errors: [`DIRECTORY.md: ${err.message}`] }; }
    const diff = firstDifference(actual, rendered);
    if (diff) errors.push(diff);
  }
  return { ok: errors.length === 0, notes, errors, count: inventory.files.size };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length && !["--check", "--write"].includes(args[0]))) {
    console.error("usage: node templates/directory-gen.mjs [--check | --write]");
    process.exitCode = 2;
  } else {
    try {
      const result = checkDirectory(ROOT, { write: args[0] === "--write" });
      for (const note of result.notes) console.log(`note: ${note}`);
      for (const err of result.errors) console.error(err);
      if (result.ok) console.log(`directory: ${args[0] === "--write" ? "written" : "check passed"}; ${result.count} tracked files`);
      process.exitCode = result.ok ? 0 : 1;
    } catch (err) { console.error(`directory: ${err.message}`); process.exitCode = 1; }
  }
}
