// Sandboxed live proof of the project .codex artifact wall. It makes a disposable K project,
// calls the exact three hook modes, demonstrates a fake done blocked, then supplies evidence.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
const TPL = path.dirname(fileURLToPath(import.meta.url));
const K = fs.mkdtempSync(path.join(os.tmpdir(), "K-artifact-wall-"));
const H = path.join(K, ".codex", "hooks"); fs.mkdirSync(H, { recursive: true });
fs.copyFileSync(path.join(TPL, "artifact-gauntlet.mjs"), path.join(H, "artifact-gauntlet.mjs"));
fs.copyFileSync(path.join(TPL, "artifact-gauntlet.example.json"), path.join(K, ".codex", "artifact-gauntlet.json"));
let pass = 0, fail = 0;
const ok = (name, yes) => { if (yes) pass++; else { fail++; console.error("FAIL: " + name); } };
const run = (mode, payload = {}) => spawnSync(process.execPath, [path.join(H, "artifact-gauntlet.mjs"), mode], { cwd: K, input: JSON.stringify(payload), encoding: "utf8" });
const context = (r) => { try { return JSON.parse(r.stdout).hookSpecificOutput; } catch { return {}; } };
const patch = (name = "src/app.ts") => ({ tool_name: "apply_patch", tool_input: { patch: `*** Update File: ${name}\n@@\n-old\n+new\n` } });
let tick = Date.now() + 60_000;
const evidence = (name, data) => {
  const file = path.join(K, ".codex", "evidence", name);
  fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, data);
  const at = new Date(tick += 1_000); fs.utimesSync(file, at, at);
};
let r = run("spec-nudge", { prompt: "finish the HEAVY task" });
ok("spec nudge gives the configuration instruction", /taskClass/.test(context(r).additionalContext || ""));
r = run("ui-track", patch()); ok("apply_patch is tracked", /tracked/.test(context(r).additionalContext || ""));
r = run("done-wall"); ok("K fake done is blocked without artifacts", context(r).permissionDecision === "deny" && /test\.log/.test(context(r).permissionDecisionReason || ""));
evidence("test.log", "tests passed\nexit: 0\n");
r = run("done-wall"); ok("K passes once a fresh passing test log exists", /PASS/.test(context(r).additionalContext || ""));
const cfg = JSON.parse(fs.readFileSync(path.join(K, ".codex", "artifact-gauntlet.json"))); cfg.taskClass = "ui"; fs.writeFileSync(path.join(K, ".codex", "artifact-gauntlet.json"), JSON.stringify(cfg));
r = run("ui-track", patch("src/screen.tsx"));
evidence("test.log", "tests passed\nstatus: 0\n");
r = run("done-wall"); ok("UI work blocks without a screenshot", context(r).permissionDecision === "deny" && /ui\.png/.test(context(r).permissionDecisionReason || ""));
evidence("ui.png", Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]));
r = run("done-wall"); ok("UI pass requires a real fresh PNG and test log", /PASS/.test(context(r).additionalContext || ""));
r = run("ui-track", patch());
fs.rmSync(path.join(K, ".codex", "evidence"), { recursive: true, force: true });
for (let i = 0; i < 3; i++) r = run("done-wall");
r = run("done-wall"); ok("MAX_NAG fail-open ceiling releases a broken wall", /FAIL-OPEN/.test(context(r).additionalContext || ""));
const wiring = JSON.parse(fs.readFileSync(path.join(TPL, "project-hooks.json")));
ok("project wiring uses apply_patch on PostToolUse", wiring.hooks.PostToolUse[0].matcher === "apply_patch");
ok("project wiring includes Stop and UserPromptSubmit", !!wiring.hooks.Stop && !!wiring.hooks.UserPromptSubmit);
fs.rmSync(K, { recursive: true, force: true });
console.log(`\nartifact gauntlet: ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
