import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
const TPL = path.dirname(fileURLToPath(import.meta.url));
const HOME = fs.mkdtempSync(path.join(os.tmpdir(), "codex-prepush-"));
const REPO = path.join(HOME, "repo"), OTHER = path.join(HOME, "other");
for (const repo of [REPO, OTHER]) spawnSync("git", ["init", "-q", repo], { encoding: "utf8" });
const TOKEN = path.join(HOME, ".codex", "PUSH_GO"), HOOK = path.join(TPL, "pre-push");
const env = { ...process.env, USERPROFILE: HOME, HOME };
let pass = 0, fail = 0;
const ok = (label, yes) => { if (yes) pass++; else { fail++; console.error("FAIL: " + label); } };
const run = () => spawnSync(process.execPath, [HOOK], { cwd: REPO, env, encoding: "utf8" });
const go = (repo = REPO) => { fs.mkdirSync(path.dirname(TOKEN), { recursive: true }); fs.writeFileSync(TOKEN, JSON.stringify({ repo, issuedAt: new Date().toISOString() })); };
const absent = () => !fs.existsSync(TOKEN);
let r = run(); ok("no token blocks", r.status !== 0 && /BLOCKED/.test(r.stderr));
go(); r = run(); ok("matching token allows and consumes", r.status === 0 && absent());
r = run(); ok("second attempt blocks", r.status !== 0 && /BLOCKED/.test(r.stderr));
go(OTHER); r = run(); ok("wrong-repo token blocks and consumes", r.status !== 0 && absent());
go(); const old = new Date(Date.now() - 31 * 60 * 1000); fs.utimesSync(TOKEN, old, old); r = run(); ok("expired token blocks and consumes", r.status !== 0 && absent());
go(); fs.writeFileSync(TOKEN, "not json"); r = run(); ok("invalid token blocks and consumes", r.status !== 0 && absent());
ok("template documents per-clone arming", /per-clone and unversioned/.test(fs.readFileSync(HOOK, "utf8")));
fs.rmSync(HOME, { recursive: true, force: true });
console.log(`\ncodex pre-push: ${pass} passed, ${fail} failed`); process.exit(fail ? 1 : 0);
