import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
const TPL = path.dirname(fileURLToPath(import.meta.url));
const HOME = fs.mkdtempSync(path.join(os.tmpdir(), "codex-prepush-"));
const REPO = path.join(HOME, "repo"), OTHER = path.join(HOME, "other");
for (const repo of [REPO, OTHER]) spawnSync("git", ["init", "-q", repo], { encoding: "utf8" });
const TOKEN = path.join(HOME, ".codex", "PUSH_GO"), HOOK = path.join(TPL, "pre-push");
const env = { ...process.env, USERPROFILE: HOME, HOME };
const HOOKS = path.join(HOME, ".codex", "hooks");
fs.mkdirSync(HOOKS, { recursive: true });
for (const f of ["codex-guard.mjs", "codex-guard-runner.mjs"])
  fs.copyFileSync(path.join(TPL, f), path.join(HOOKS, f));
fs.copyFileSync(path.join(TPL, "..", "hooks", "push-guard.mjs"), path.join(HOOKS, "push-guard.mjs"));
const LAUNCHER = path.join(HOOKS, "codex-guard-runner.mjs");
let pass = 0, fail = 0;
const ok = (label, yes) => { if (yes) pass++; else { fail++; console.error("FAIL: " + label); } };
const run = () => spawnSync(process.execPath, [HOOK], { cwd: REPO, env, encoding: "utf8" });
const launch = () => spawnSync(process.execPath, [LAUNCHER], {
  input: JSON.stringify({ cwd: REPO, tool_name: "Bash", tool_input: { command: "git push origin HEAD" } }), env, encoding: "utf8",
});
const go = (repo = REPO) => { fs.mkdirSync(path.dirname(TOKEN), { recursive: true }); fs.writeFileSync(TOKEN, JSON.stringify({ repo, issuedAt: new Date().toISOString() })); };
const absent = () => !fs.existsSync(TOKEN);
const claimed = () => { try { return typeof JSON.parse(fs.readFileSync(TOKEN, "utf8")).claimedAt === "string"; } catch { return false; } };
let r = run(); ok("no token blocks", r.status !== 0 && /BLOCKED/.test(r.stderr));
go(); r = run(); ok("matching token allows and consumes", r.status === 0 && absent());
r = run(); ok("second attempt blocks", r.status !== 0 && /BLOCKED/.test(r.stderr));
go(OTHER); r = run(); ok("wrong-repo token blocks and consumes", r.status !== 0 && absent());
go(); fs.writeFileSync(TOKEN, JSON.stringify({ repo: REPO, issuedAt: new Date(Date.now() - 31 * 60 * 1000).toISOString() })); r = run(); ok("expired token blocks and consumes", r.status !== 0 && absent());
go(); fs.writeFileSync(TOKEN, "not json"); r = run(); ok("invalid token blocks and consumes", r.status !== 0 && absent());
go(); r = launch(); ok("launcher claims one token", r.status === 0 && claimed());
r = run(); ok("launcher then pre-push allows exactly once and consumes", r.status === 0 && absent());
r = launch(); const launcherDenied = /permissionDecision":"deny"/.test(r.stdout);
r = run(); ok("after the handoff, a second push is denied by both layers", launcherDenied && r.status !== 0 && /BLOCKED/.test(r.stderr));
go(); r = run(); ok("bypass pre-push accepts an unclaimed token once", r.status === 0 && absent());
go(); r = launch();
const abandoned = JSON.parse(fs.readFileSync(TOKEN, "utf8")); abandoned.claimedAt = new Date(Date.now() - 6 * 60 * 1000).toISOString(); fs.writeFileSync(TOKEN, JSON.stringify(abandoned));
r = run(); ok("a claimed-but-abandoned token is denied and consumed", r.status !== 0 && /claim is stale/.test(r.stderr) && absent());
ok("template documents per-clone arming", /per-clone and unversioned/.test(fs.readFileSync(HOOK, "utf8")));
// Exercise Git's hook discovery and the LF shebang against a local throwaway bare repository.
// This is an isolated fixture push, with no network, credentials, or live GO token.
const bare = path.join(HOME, "fixture-remote.git");
const git = (cwd, ...args) => spawnSync("git", args, { cwd, env, encoding: "utf8", windowsHide: true });
git(HOME, "init", "--bare", "-q", bare);
fs.writeFileSync(path.join(REPO, "fixture.txt"), "offline hook test\n");
git(REPO, "add", "fixture.txt");
const commit = git(REPO, "-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid", "-c", "commit.gpgsign=false", "commit", "-qm", "fixture");
if (commit.status !== 0) throw new Error("fixture commit failed: " + commit.stderr);
fs.copyFileSync(HOOK, path.join(REPO, ".git/hooks/pre-push"));
fs.chmodSync(path.join(REPO, ".git/hooks/pre-push"), 0o755);
r = git(REPO, "push", bare, "HEAD:refs/heads/fixture");
ok("Git invokes the installed hook and blocks without a token", r.status !== 0 && /codex-pre-push.*BLOCKED/.test(r.stderr));
go();
r = git(REPO, "push", bare, "HEAD:refs/heads/fixture");
ok("Git accepts the installed LF hook and consumes a fixture token once", r.status === 0 && absent() && /GO token consumed/.test(r.stderr));
if (path.dirname(path.resolve(HOME)) !== path.resolve(os.tmpdir()) || !path.basename(HOME).startsWith("codex-prepush-")) throw new Error("unsafe cleanup target");
fs.rmSync(HOME, { recursive: true, force: true });
console.log(`\ncodex pre-push: ${pass} passed, ${fail} failed`); process.exit(fail ? 1 : 0);
